name: CI • Commit
run-name: 'CI • Commit • ${{ github.ref_name }}'

on:
    push:
        branches:
            - 'feature/**'
            - 'bugfix/**'
            - 'task/**'
            - 'hotfix/**'
            - 'chore/**'

concurrency:
    group: ci-commit-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint (ESLint)
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install deps
              run: npm install --no-audit --no-fund

            - name: Lint
              run: npm run lint
