name: CI • Commit
run-name: 'CI • Commit • ${{ github.ref_name }}'

on:
    push:
        branches:
            - 'feature/**'
            - 'bugfix/**'
            - 'task/**'
            - 'hotfix/**'
            - 'chore/**'

concurrency:
    group: ci-commit-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint (ESLint)
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - name: Install deps (npm ci)
              run: npm ci --no-audit --no-fund
            - name: Lint
              run: npm run lint
